# SPDX-FileCopyrightText: 2021 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2021 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_netplan
    image: jrei/systemd-ubuntu:20.04
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network_mode: 'default'
    docker_networks:
      - name: 'netplan_network'
        ipam_config:
          - subnet: '10.1.0.0/24'
    networks:
      - name: 'netplan_network'
        ipv4_address: '10.1.0.2'
lint: |
  yamllint --strict --format colored .
  ansible-lint -v --force-color --exclude .pipenv/ .
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: ansible

...
